.\" generated with Ronn-NG/v0.10.1
.\" http://github.com/apjanke/ronn-ng/tree/0.10.1
.TH "REPOSITORY\-DIST\-WIZARD" "1" "January 2020" "repository-dist" "repository-dist Manual"
.SH "NAME"
\fBrepository\-dist\-wizard\fR \- enable, configure or disable derivative distribution apt repository
.SH "SYNOPSIS"
\fBrepository\-dist\-wizard\fR
.SH "DESCRIPTION"
Graphical user interface for \fBrepository\-dist\fR tool\.
.SH "WWW"
https://www\.whonix\.org/wiki/Project\-APT\-Repository
.SH "AUTHOR"
This man page has been written by Patrick Schleizer (adrelanos@whonix\.org)\.
