.\" generated with Ronn-NG/v0.8.0
.\" http://github.com/apjanke/ronn-ng/tree/0.8.0
.TH "WHONIX\-REPOSITORY\-WIZARD" "1" "January 2020" "whonix-repository" "whonix-repository Manual"
.SH "NAME"
\fBwhonix\-repository\-wizard\fR \- enable, configure or disable Whonix apt repository
.P
.SH "SYNOPSIS"
\fBwhonix\-repository\-wizard\fR
.SH "DESCRIPTION"
Graphical user interface for \fBrepository\-dist\fR tool\.
.SH "WWW"
https://www\.whonix\.org/wiki/Whonix\-APT\-Repository
.SH "AUTHOR"
This man page has been written by Patrick Schleizer (adrelanos@riseup\.net)\.
