#!/usr/bin/python3 -u

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

from subprocess import call
import sys, os
import time
import shutil

command = 'xhost +local:root'
call(command, shell = True)

whonix_repository_wizard = shutil.which("whonix-repository-wizard")
if whonix_repository_wizard == None:
    print('ERROR: whonix-repository-wizard not found! Exiting.')
    sys.exit(1)

command = 'kdesudo {}'.format(whonix_repository_wizard)
call(command, shell=True)
